// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWMAEcgQ15WHGV9BOW-gGC-AN3xbmkQwU',
    appId: '1:191365853067:web:c361a3d9f5b31bc489098e',
    messagingSenderId: '191365853067',
    projectId: 'chat-app-7b906',
    authDomain: 'chat-app-7b906.firebaseapp.com',
    storageBucket: 'chat-app-7b906.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk9ib4onHRTDLzQ8XYHXoxVVh_ZDfskus',
    appId: '1:191365853067:android:5542d9412c8b9ce289098e',
    messagingSenderId: '191365853067',
    projectId: 'chat-app-7b906',
    storageBucket: 'chat-app-7b906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcQDu7QRyvAJgL4_Y-pg1EPm8dJwButyQ',
    appId: '1:191365853067:ios:8390226d29abdcfc89098e',
    messagingSenderId: '191365853067',
    projectId: 'chat-app-7b906',
    storageBucket: 'chat-app-7b906.appspot.com',
    androidClientId: '191365853067-ak58g3ho5r9se6ifrh3sigs4ehvjotfl.apps.googleusercontent.com',
    iosClientId: '191365853067-qcf6qpmdl9bs8ifb8fvpa95iutflo7s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcQDu7QRyvAJgL4_Y-pg1EPm8dJwButyQ',
    appId: '1:191365853067:ios:c5f0efa2bf39568689098e',
    messagingSenderId: '191365853067',
    projectId: 'chat-app-7b906',
    storageBucket: 'chat-app-7b906.appspot.com',
    androidClientId: '191365853067-ak58g3ho5r9se6ifrh3sigs4ehvjotfl.apps.googleusercontent.com',
    iosClientId: '191365853067-963h8vkijcltgjld4gh0an9q0n3d17ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
